name: 🚀 Umbraco Cloud Deployment

# Trigger when committing to main branch
on:
  push:
    branches:
     - main

jobs:
  # Try to sync the local repository to get up to speed with any changes in Cloud project
  cloud-sync:
    name: "Synchronize with Cloud"
    uses: ./.github/workflows/cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
      
  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: cloud-sync
    uses: ./.github/workflows/cloud-deployment.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
